[project]
name = "perplexity-webui-scraper"
version = "0.1.3"
description = "Perplexity WebUI Scraper"
readme = "README.md"
authors = [
    { name = "henrique-coder", email = "henriquemoreira10fk@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "orjson>=3.11.3",
    "pydantic>=2.0.0",
]

[dependency-groups]
dev = [
    "camoufox",
    "fastapi",
    "python-dotenv",
    "rich",
    "uvicorn",
]
lint = [
    "ruff",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
